### ISSUE TITLE
Notify other users when someone joins/leaves the meet

### ISSUE THREAD

**Issue by fampiyush** [fampiyush/virtual-meet#1]
A small notification should be shown whenever someone joins or leaves the meeting.

**Comment by Atharva-Nimbalkar** [comment]
> A small notification should be shown whenever someone joins or leaves the meeting.

Hello @fampiyush i want to contribute to this issue, can u please assign me?

**Comment by fampiyush** [comment]
@Atharva-Nimbalkar

**Comment by Atharva-Nimbalkar** [comment]
> @Atharva-Nimbalkar

hello @fampiyush ,i need your help,actually after npm run dev .my frontend run on 5173 port properly but backend is not running at port 3000 even after i done proper backend setup 
follwoing error  i get at console

""
socket__io-client.js?v=4ad226ba:898 
 GET http://localhost:3000/socket.io/?EIO=4&transport=polling&t=OxXjOfo net::ERR_CONNECTION_REFUSED
 """

**Comment by fampiyush** [comment]
Are u getting the welcome message on navigating to localhost:3000 ? @Atharva-Nimbalkar

**Comment by Atharva-Nimbalkar** [comment]
> Are u getting the welcome message on navigating to localhost:3000 ? @Atharva-Nimbalkar

No only get "This site can’t be reached" @fampiyush

**Comment by fampiyush** [comment]
You are probably not running the backend then. Navigate to backend location and do node index.js, to run it, and then try

**Comment by fampiyush** [comment]
Are you still working on this ? @Atharva-Nimbalkar

**Comment by Atharva-Nimbalkar** [comment]
> Are you still working on this ? @Atharva-Nimbalkar

I was working, but now my exams are going so you can unassign me.Later i will try to resolve issue once again. Thank you
